name: Task 1.2 # Run Bandit on a new pull request on the main branch and reject if any High issues are found
on:
  pull_request:
    branches:
      - main
    

jobs:
  run-bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        #run: bandit -r . --severity-level high -f json -o bandit-high-report.json
        uses: PyCQA/bandit-action@v1.0.0
        with:
          severity: high
        

      - name: Publish Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: Bandit Report
          path: results.sarif
        
      - name: Check Bandit Report for High Severity Issues
        run: |
            if grep -q '"issue_severity": "HIGH"' results.sarif; then 
              echo "::error:: High severity issues found in Bandit scan. Rejecting the pull request." 
            else 
              echo "No high severity issues found in Bandit scan." 
            fi